// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMbXW2XUgXPkCIo2a9fzOKEm8SlyKqg0E',
    appId: '1:586146725745:android:737159ad974c73b373c0d0',
    messagingSenderId: '586146725745',
    projectId: 'blbla-3f68c',
    storageBucket: 'blbla-3f68c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRxHJG_mLgT8MTMSzLvXyuqTpERmnUYqo',
    appId: '1:586146725745:ios:0a1cbd8848b1f6a173c0d0',
    messagingSenderId: '586146725745',
    projectId: 'blbla-3f68c',
    storageBucket: 'blbla-3f68c.firebasestorage.app',
    iosBundleId: 'com.example.blbla',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCoiS3BATeikOPIrmZQP2mIhfBMipZCARw',
    appId: '1:586146725745:web:79c2b30e8dd31c0273c0d0',
    messagingSenderId: '586146725745',
    projectId: 'blbla-3f68c',
    authDomain: 'blbla-3f68c.firebaseapp.com',
    storageBucket: 'blbla-3f68c.firebasestorage.app',
  );

}